import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/theme/ThemeProvider";
import clsx from "clsx";
import { Header } from "@/src/feature/layout/Header";
import Footer from "@/src/feature/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MERN Social APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body className={clsx(inter.className, 'bg-background')}>
          <div className="flex flex-col h-full">
            <Header />
          </div>
          <div className="flex-1 max-w-lg m-auto py-12 w-full">{children}</div>
            <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
